#!/bin/sh

./convert < input > solution.dzn

minizinc                            \
    -p 8                            \
    --no-output-comments            \
    --solver com.google.ortools.sat \
    solution.mzn                    \
    solution.dzn
